### ISSUE TITLE
StaffController

### ISSUE THREAD

**Issue by ghermans** [idevelopment/RingMe#1]
When you choose to run Ring Me in standalone mode we will need some migrations & models to get our users logged in.

#### Todo
- [x] Create new user wizard 
- [x] Create edit view
- [x] Add destroy user method.
- [x] Add edit logic. 
- [x] Save user <- description plz - @ghermans

**Comment by Tjoosten** [comment]
I made a seprate issue for the roles.
