### ISSUE TITLE
Change the New customer form to wizard

### ISSUE THREAD

**Issue by ghermans** [idevelopment/RingMe#109]
## Steps for this wizard
- Personal details
- Product details
- Account details

#### Personal details
- company
- VAT number 
- Name
- Firstname
- address
- postalcode
- city
- country
- email
- phone
-mobile

### Products
- Select multiple products for the user.

### Account details
- Login & password

**Comment by ghermans** [comment]
The new register form has been pushed.

**Comment by ghermans** [comment]
## Todo 

- [ ] Save the customer to the db
- [ ] Assign the guest role to the customer
- [ ] Assign products to the customers
- [ ] Send confirmation email to the customer.

**Comment by Tjoosten** [comment]
@ghermans need help?

**Comment by ghermans** [comment]
No i will take fix this, thx anyway.

**Comment by ghermans** [comment]
#108  Asset management needs to be fixed first.
