### ISSUE TITLE
CustomerController

### ISSUE THREAD

**Issue by ghermans** [idevelopment/RingMe#14]
## Completed
- [X] Create customer controller.
- [X] Create customer index view.
- [x] Create customer migration file.
- [x] Create customer model.
- [x] Create customer registration view.

## Todo
- [ ] Create store method in CustomerController.
